#version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/halther/backend 
    networks:
      - app-network

  frontend:
    environment:
      - NODE_ENV=${NODE_ENV}
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
