name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest #necesito este runner

    steps:
    # Checkout del código
    - name: Checkout code
      uses: actions/checkout@v3

    # Configurar Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Construir y subir las imágenes tanto back como front
    - name: Build and Push Backend Docker Image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/flask-backend:latest
        context: backend
        file: backend/Dockerfile
        cache-to: type=inline
    
    - name: Build and Push Frontend Docker Image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/vue-frontend:latest
        context: frontend
        file: frontend/Dockerfile
        cache-to: type=inline

    # Deploy to AWS EC2
    - name: Deploy to AWS
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose
          docker pull ${{ secrets.DOCKER_USERNAME }}/flask-backend:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/vue-frontend:latest
          docker-compose -f ~/halther/docker-compose.yml up -d
