name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest #necesito este runner

    steps:
    # Checkout del código
    - name: Checkout code
      uses: actions/checkout@v3

    # Configurar Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: List files in backend directory
      run: ls -R backend

    # Construir y subir las imágenes tanto back como front
    - name: Build and Push Backend Docker Image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/flask-backend:latest
        context: .
        file: backend/Dockerfile
    
    - name: Build and Push Frontend Docker Image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/vue-frontend:latest
        context: .
        file: frontend/Dockerfile

    # Deploy to AWS EC2
    - name: Deploy to AWS
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          sudo yum update -y
          sudo yum install -y docker
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          sudo usermod -aG docker ec2-user
          docker-compose --version
          docker ps
          docker-compose down
          docker ps
          docker pull ${{ secrets.DOCKER_USERNAME }}/flask-backend:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/vue-frontend:latest
          docker-compose -f ~/halther/docker-compose.yml up --build -d
